-- =============================================================
-- Fraud Scores Table
-- Stores deterministic risk scores for each batch, generated by
-- the AgroDex Fraud Pattern Detection & Risk Prediction Engine.
-- Gemini AI generates the human-readable explanation only;
-- all numerical scoring is done deterministically in the backend.
-- =============================================================

-- Drop existing policies if re-running
DROP POLICY IF EXISTS "anon read fraud_scores" ON fraud_scores;
DROP POLICY IF EXISTS "service role full fraud_scores" ON fraud_scores;

-- Create the fraud_scores table
CREATE TABLE IF NOT EXISTS fraud_scores (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_id       UUID        NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
  farmer_id      UUID,       -- Supabase auth user UUID (nullable for legacy batches without farmer_id)
  risk_score     INTEGER     NOT NULL CHECK (risk_score BETWEEN 0 AND 100),
  risk_level     TEXT        NOT NULL CHECK (risk_level IN ('SAFE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
  reasons        JSONB       NOT NULL DEFAULT '[]'::jsonb,
  ai_explanation TEXT,
  generated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Comments for documentation
COMMENT ON TABLE  fraud_scores              IS 'Deterministic fraud risk scores for agricultural batches. Scores computed by rule engine; Gemini generates explanation text only.';
COMMENT ON COLUMN fraud_scores.risk_score   IS '0–100 weighted rule score. 0=no signals, 100=max fraud signals.';
COMMENT ON COLUMN fraud_scores.risk_level   IS 'SAFE(0-19) | LOW(20-34) | MEDIUM(35-54) | HIGH(55-74) | CRITICAL(75-100)';
COMMENT ON COLUMN fraud_scores.reasons      IS 'JSONB array of detected fraud signal objects {signal, weight, description}';
COMMENT ON COLUMN fraud_scores.ai_explanation IS 'Gemini-generated narrative explanation of detected fraud signals (explanation only, not scoring)';
COMMENT ON COLUMN fraud_scores.generated_at IS 'When the fraud analysis was run; used for cache invalidation (>1 hour triggers re-analysis)';

-- Unique constraint: one score per batch (upsert on batch_id)
CREATE UNIQUE INDEX IF NOT EXISTS idx_fraud_scores_batch_id ON fraud_scores(batch_id);

-- Performance indexes
CREATE INDEX IF NOT EXISTS idx_fraud_scores_farmer_id    ON fraud_scores(farmer_id);
CREATE INDEX IF NOT EXISTS idx_fraud_scores_risk_level   ON fraud_scores(risk_level);
CREATE INDEX IF NOT EXISTS idx_fraud_scores_generated_at ON fraud_scores(generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_fraud_scores_risk_score   ON fraud_scores(risk_score DESC);

-- Enable Row Level Security
ALTER TABLE fraud_scores ENABLE ROW LEVEL SECURITY;

-- Allow public read access (fraud overview is public-facing)
CREATE POLICY "anon read fraud_scores"
  ON fraud_scores FOR SELECT
  TO anon
  USING (true);

-- Service role has full access for backend writes
CREATE POLICY "service role full fraud_scores"
  ON fraud_scores FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
