import { useMemo, useCallback } from "react";
import { useNavigate } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import {
  Bot,
  ChevronRight,
  ChevronLeft,
  X,
  Sparkles,
  Globe,
  Lightbulb,
  Sprout,
  CheckCircle2,
  FileText,
  Download,
  Camera,
  StepForward,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { useToast } from "@/hooks/use-toast";
import { InteractiveTimeline } from "./InteractiveTimeline";
import { TrustSignalAccordion } from "./TrustSignalAccordion";
import {
  ContextualRecommendations,
  generateRecommendations,
  type Recommendation,
} from "./ContextualRecommendations";
import {
  useVerificationAssistant,
  type TimelineStep,
  type TrustSignal,
  type GuideStep,
} from "@/context/VerificationAssistantContext";

const DEMO_TIMELINE: TimelineStep[] = [
  { step: 1, event: "Batch Registered on Hedera", timestamp: "2025-10-28T09:00:00Z", txId: "0.0.7170927@1730102400.000000000", status: "verified" },
  { step: 2, event: "AI Quality Assessment", timestamp: "2025-10-28T09:15:00Z", txId: "0.0.7170927@1730103300.000000001", status: "verified" },
  { step: 3, event: "NFT Certificate Minted", timestamp: "2025-10-28T10:00:00Z", txId: "0.0.7170927@1730106000.000000002", status: "verified" },
  { step: 4, event: "Supply Chain Transfer", timestamp: "2025-10-30T14:30:00Z", txId: "0.0.7170927@1730284200.000000003", status: "verified" },
  { step: 5, event: "Market Verification", timestamp: "2025-11-02T08:00:00Z", txId: "0.0.7170927@1730524800.000000004", status: "pending" },
];

const DEMO_SIGNALS: TrustSignal[] = [
  {
    id: "status",
    title: "Batch Status: Verified",
    status: "verified",
    plainExplanation: "This status shows whether the batch has been fully verified on the Hedera blockchain. A 'Verified' status means all records have been checked and confirmed.",
    technicalDetail: "status=verified, verifiedAt present: true",
  },
  {
    id: "hcs-trail",
    title: "Blockchain Transaction Trail",
    status: "verified",
    plainExplanation: "Each of these transactions is a record permanently stored on the Hedera network. Like a digital timestamp that no one can alter.",
    technicalDetail: "5 transaction(s) anchored to Hedera testnet",
  },
  {
    id: "trust-score",
    title: "AI Trust Score: 92/100",
    status: "verified",
    plainExplanation: "High trust score! The batch data is consistent, certifications are valid, and the supply chain history is verifiable.",
    technicalDetail: "score=92, explanation=High data consistency across all sources",
  },
  {
    id: "ai-provenance",
    title: "AI Provenance Analysis",
    status: "verified",
    plainExplanation: "AI has analyzed all batch data and provided a summary about the product's origin and journey. This helps you quickly understand the product's history.",
    technicalDetail: "Generated by Google Gemini AI",
  },
];

const guideSteps = [
  {
    step: 1 as GuideStep,
    icon: CheckCircle2,
    titleKey: "Guide what is this",
    titleId: "Apa Itu Verifikasi?",
    title: "What Is Verification?",
    descriptionKey: "verify.guide.step1",
    description:
      "Blockchain verification confirms that a product's records are authentic and haven't been tampered with. Think of it as a digital fingerprint for every batch.",
    descriptionId:
      "Verifikasi blockchain memastikan bahwa catatan produk autentik dan tidak dimanipulasi. Anggap saja sebagai sidik jari digital untuk setiap batch.",
  },
  {
    step: 2 as GuideStep,
    icon: Sprout,
    titleKey: "verify.guide.step2Title",
    title: "Tracking the Journey",
    titleId: "Melacak Perjalanan",
    descriptionKey: "verify.guide.step2",
    description:
      "Each step — from harvest to market — is recorded on Hedera. You can inspect every event in the timeline below to see exactly what happened and when.",
    descriptionId:
      "Setiap langkah — dari panen hingga pasar — dicatat di Hedera. Anda dapat memeriksa setiap peristiwa dalam linimasa untuk melihat apa yang terjadi dan kapan.",
  },
  {
    step: 3 as GuideStep,
    icon: Sparkles,
    titleKey: "verify.guide.step3Title",
    title: "Trust Signals",
    titleId: "Sinyal Kepercayaan",
    descriptionKey: "verify.guide.step3",
    description:
      "Green checkmarks mean a signal passed. Amber means pending. Red means attention needed. Tap any signal to learn what it means in plain language.",
    descriptionId:
      "Centang hijau berarti sinyal lulus. Kuning berarti tertunda. Merah berarti perlu perhatian. Ketuk sinyal apa pun untuk mempelajari artinya dalam bahasa sehari-hari.",
  },
  {
    step: 4 as GuideStep,
    icon: Lightbulb,
    titleKey: "verify.guide.step4Title",
    title: "What You Can Do",
    titleId: "Yang Dapat Anda Lakukan",
    descriptionKey: "verify.guide.step4",
    description:
      "Based on the verification results, we provide personalized recommendations — whether that's downloading a certificate, scanning another QR code, or contacting the supplier.",
    descriptionId:
      "Berdasarkan hasil verifikasi, kami memberikan rekomendasi personal — apakah itu mengunduh sertifikat, memindai kode QR lain, atau menghubungi pemasok.",
  },
];

interface VerificationAssistantProps {
  verifiedResult?: {
    tokenId?: string;
    serialNumber?: string;
    status?: string;
    verifiedAt?: string;
    hcsTransactionIds?: string[];
    hcsMessages?: unknown[];
    ai_summary?: {
      trustScore?: number;
      trustExplanation?: string;
      summary_en?: string;
      summary_fr?: string;
      timeline?: Array<{
        timestamp: string;
        event: string;
        txId: string;
      }>;
    };
    batch?: {
      id?: string;
      batch_name?: string;
      product_type?: string;
    };
  } | null;
  onExportPDF?: () => void;
  onOpenScanner?: () => void;
  demo?: boolean;
}

export function VerificationAssistant({
  verifiedResult,
  onExportPDF,
  onOpenScanner,
  demo,
}: VerificationAssistantProps) {
  const { state, setGuideStep, toggleGuide, setAssistantLanguage } =
    useVerificationAssistant();
  const navigate = useNavigate();
  const { toast } = useToast();

  const isIndonesian = state.assistantLanguage === "id";

  const batchId = verifiedResult?.batch?.id;

  const handleShareProof = useCallback(() => {
    const url = window.location.href;
    const text = isIndonesian
      ? `Lihat hasil verifikasi produk AgroDex: ${url}`
      : `Check out this AgroDex product verification: ${url}`;

    if (navigator.share) {
      navigator.share({ title: "AgroDex Verification", text, url }).catch(() => {
        // User cancelled or error — fall back to clipboard
      });
    } else {
      navigator.clipboard.writeText(url).then(() => {
        toast({
          title: isIndonesian ? "Tautan disalin" : "Link copied",
          description: isIndonesian
            ? "Tautan verifikasi telah disalin ke papan klip."
            : "Verification link has been copied to your clipboard.",
        });
      });
    }
  }, [isIndonesian, toast]);

  const handleExploreJourney = useCallback(() => {
    if (batchId) {
      navigate(`/journey/${batchId}`);
    }
  }, [batchId, navigate]);

  const timelineSteps: TimelineStep[] = useMemo(() => {
    if (demo) {
      return isIndonesian ? [
        { step: 1, event: "Batch Terdaftar di Hedera", timestamp: "2025-10-28T09:00:00Z", txId: "0.0.7170927@1730102400.000000000", status: "verified" },
        { step: 2, event: "Penilaian Kualitas AI", timestamp: "2025-10-28T09:15:00Z", txId: "0.0.7170927@1730103300.000000001", status: "verified" },
        { step: 3, event: "Sertifikat NFT Dicetak", timestamp: "2025-10-28T10:00:00Z", txId: "0.0.7170927@1730106000.000000002", status: "verified" },
        { step: 4, event: "Transfer Rantai Pasok", timestamp: "2025-10-30T14:30:00Z", txId: "0.0.7170927@1730284200.000000003", status: "verified" },
        { step: 5, event: "Verifikasi Pasar", timestamp: "2025-11-02T08:00:00Z", txId: "0.0.7170927@1730524800.000000004", status: "pending" },
      ] : DEMO_TIMELINE;
    }
    const result: TimelineStep[] = [];
    const vr = verifiedResult;

    // 1. Add steps from AI summary timeline (e.g. "Batch Registered on HCS")
    if (vr?.ai_summary?.timeline) {
      vr.ai_summary.timeline?.forEach((item, idx) => {
        result.push({
          step: idx + 1,
          event: item.event,
          timestamp: item.timestamp,
          txId: item.txId,
          status: "verified",
        });
      });
    }

    // 2. Add steps from HCS transaction IDs not already covered
    if (vr?.hcsTransactionIds) {
      vr.hcsTransactionIds?.forEach((txId, idx) => {
        if (!result.some((r) => r.txId === txId)) {
          result.push({
            step: result.length + 1,
            event: isIndonesian ? `Transaksi HCS #${idx + 1}` : `HCS Transaction #${idx + 1}`,
            timestamp: new Date().toISOString(),
            txId,
            status: "verified",
          });
        }
      });
    }

    // 3. If the batch is registered but NOT tokenized, add an "Awaiting Tokenization" step
    if (vr?.status === "registered" && !vr?.tokenId) {
      result.push({
        step: result.length + 1,
        event: isIndonesian ? "Menunggu Tokenisasi NFT" : "Awaiting NFT Tokenization",
        timestamp: vr?.verifiedAt || new Date().toISOString(),
        txId: vr?.hcsTransactionIds?.[0] || "",
        status: "pending",
      });
    }

    // 4. Add a final verification step using the current result status
    result.push({
      step: result.length + 1,
      event: vr?.status === "registered"
        ? (isIndonesian ? "Pendaftaran Diverifikasi di Hedera" : "Registration Verified on Hedera")
        : (isIndonesian ? "Verifikasi Batch Selesai" : "Batch Verification Complete"),
      timestamp: vr?.verifiedAt || new Date().toISOString(),
      txId: vr?.hcsTransactionIds?.[0] || "",
      status: "verified",
    });

    return result;
  }, [verifiedResult, isIndonesian, demo]);

  const trustSignals: TrustSignal[] = useMemo(() => {
    if (demo) return DEMO_SIGNALS.map((s) => ({
      ...s,
      title: isIndonesian
        ? s.id === "status" ? "Status Batch: Terverifikasi"
          : s.id === "hcs-trail" ? "Jejak Transaksi Blockchain"
            : s.id === "trust-score" ? "Skor Kepercayaan AI: 92/100"
              : "Analisis Riwayat AI"
        : s.title,
      plainExplanation: isIndonesian
        ? s.id === "status" ? "Status ini menunjukkan apakah batch telah sepenuhnya diverifikasi di blockchain Hedera. Status 'Terverifikasi' berarti semua catatan telah diperiksa dan dikonfirmasi."
          : s.id === "hcs-trail" ? "Setiap transaksi ini adalah catatan yang disimpan secara permanen di jaringan Hedera. Seperti stempel waktu digital yang tidak dapat diubah oleh siapa pun."
            : s.id === "trust-score" ? "Skor kepercayaan tinggi! Data batch konsisten, sertifikasi valid, dan riwayat rantai pasok dapat diverifikasi."
              : "AI telah menganalisis semua data batch dan memberikan ringkasan tentang asal-usul dan perjalanan produk. Ini membantu Anda memahami riwayat produk secara cepat."
        : s.plainExplanation,
    }));
    const signals: TrustSignal[] = [];
    const result = verifiedResult;

    if (result?.status) {
      signals.push({
        id: "status",
        title: isIndonesian
          ? `Status Batch: ${result.status === "verified" ? "Terverifikasi" : result.status === "registered" ? "Terdaftar" : result.status}`
          : `Batch Status: ${result.status === "verified" ? "Verified" : result.status === "registered" ? "Registered" : result.status}`,
        status: result.status === "verified" ? "verified" : "pending",
        plainExplanation: isIndonesian
          ? "Status ini menunjukkan apakah batch telah sepenuhnya diverifikasi di blockchain Hedera. Status 'Terverifikasi' berarti semua catatan telah diperiksa dan dikonfirmasi."
          : "This status shows whether the batch has been fully verified on the Hedera blockchain. A 'Verified' status means all records have been checked and confirmed.",
        technicalDetail: `status=${result.status}, verifiedAt present: ${!!result.verifiedAt}`,
      });
    }

    if (result?.hcsTransactionIds && result.hcsTransactionIds.length > 0) {
      signals.push({
        id: "hcs-trail",
        title: isIndonesian
          ? "Jejak Transaksi Blockchain"
          : "Blockchain Transaction Trail",
        status: "verified",
        plainExplanation: isIndonesian
          ? "Setiap transaksi ini adalah catatan yang disimpan secara permanen di jaringan Hedera. Seperti stempel waktu digital yang tidak dapat diubah oleh siapa pun."
          : "Each of these transactions is a record permanently stored on the Hedera network. Like a digital timestamp that no one can alter.",
        technicalDetail: `${result.hcsTransactionIds.length} transaction(s) anchored to Hedera testnet`,
      });
    }

    if (result?.ai_summary?.trustScore !== null && result?.ai_summary?.trustScore !== undefined) {
      const score = result.ai_summary.trustScore;
      signals.push({
        id: "trust-score",
        title: isIndonesian
          ? `Skor Kepercayaan AI: ${score}/100`
          : `AI Trust Score: ${score}/100`,
        status: score >= 60 ? "verified" : score >= 40 ? "pending" : "failed",
        plainExplanation:
          score >= 85
            ? isIndonesian
              ? "Skor kepercayaan tinggi! Data batch konsisten, sertifikasi valid, dan riwayat rantai pasok dapat diverifikasi."
              : "High trust score! The batch data is consistent, certifications are valid, and the supply chain history is verifiable."
            : score >= 60
              ? isIndonesian
                ? "Skor kepercayaan menengah. Beberapa sinyal perlu diperiksa lebih lanjut. Tinjau rekomendasi di bawah untuk langkah selanjutnya."
                : "Medium trust score. Some signals need further review. Check the recommendations below for next steps."
              : isIndonesian
                ? "Skor kepercayaan rendah. Disarankan untuk tidak melanjutkan transaksi tanpa verifikasi dokumen tambahan."
                : "Low trust score. It is advisable not to proceed with the transaction without additional document verification.",
        technicalDetail: `score=${score}, explanation=${result.ai_summary.trustExplanation || "N/A"}`,
      });
    }

    if (result?.ai_summary?.summary_en) {
      signals.push({
        id: "ai-provenance",
        title: isIndonesian ? "Analisis Riwayat AI" : "AI Provenance Analysis",
        status: "verified",
        plainExplanation: isIndonesian
          ? "AI telah menganalisis semua data batch dan memberikan ringkasan tentang asal-usul dan perjalanan produk. Ini membantu Anda memahami riwayat produk secara cepat."
          : "AI has analyzed all batch data and provided a summary about the product's origin and journey. This helps you quickly understand the product's history.",
        technicalDetail: "Generated by Google Gemini AI",
      });
    }

    return signals;
  }, [verifiedResult, isIndonesian, demo]);

  const recommendations: Recommendation[] = useMemo(() => {
    const recs = demo
      ? [
          { id: "scan-qr", icon: Camera, title: isIndonesian ? "Pindai Kode QR" : "Scan QR Code", description: isIndonesian ? "Gunakan kamera ponsel Anda untuk memindai kode QR pada kemasan produk. Ini akan membuka halaman verifikasi secara instan." : "Use your phone camera to scan the QR code on the product packaging. This will open the verification page instantly.", priority: "high" as const, action: { label: isIndonesian ? "Buka Pemindai" : "Open Scanner", onClick: onOpenScanner } },
          { id: "export-pdf", icon: FileText, title: isIndonesian ? "Unduh Sertifikat" : "Download Certificate", description: isIndonesian ? "Simpan hasil verifikasi sebagai PDF yang dapat dibagikan dengan pembeli atau otoritas pengatur." : "Save the verification result as a PDF that can be shared with buyers or regulatory authorities.", priority: "high" as const, action: { label: isIndonesian ? "Unduh PDF" : "Download PDF", onClick: onExportPDF } },
          { id: "share-report", icon: Download, title: isIndonesian ? "Bagikan Bukti" : "Share Proof", description: isIndonesian ? "Produk kepercayaan tinggi. Bagikan laporan verifikasi ini dengan mitra rantai pasok Anda." : "High-trust product. Share this verification report with your supply chain partners.", priority: "medium" as const },
        ]
      : generateRecommendations(
          !!verifiedResult,
          verifiedResult?.ai_summary?.trustScore,
          verifiedResult?.status ?? "",
          !!verifiedResult?.hcsMessages?.length,
          isIndonesian ? "id" : "en",
        );

    // Wire up action handlers to generated recommendations
    return recs.map((rec): Recommendation => {
      switch (rec.id) {
        case "scan-qr":
          return { ...rec, action: { label: rec.action?.label ?? "", ...rec.action, onClick: onOpenScanner } };
        case "export-pdf":
          return { ...rec, action: { label: rec.action?.label ?? "", ...rec.action, onClick: onExportPDF } };
        case "share-report":
          return { ...rec, action: { label: rec.action?.label ?? (isIndonesian ? "Bagikan" : "Share"), ...rec.action, onClick: handleShareProof } };
        case "learn-more":
          return { ...rec, action: { label: rec.action?.label ?? (isIndonesian ? "Lihat Perjalanan" : "View Journey"), ...rec.action, onClick: handleExploreJourney } };
        default:
          return rec;
      }
    });
  }, [verifiedResult, isIndonesian, demo, onExportPDF, onOpenScanner, handleShareProof, handleExploreJourney]);

  const currentGuide = guideSteps[state.currentGuideStep - 1];
  const progress = (state.currentGuideStep / guideSteps.length) * 100;

  const StepIcon = currentGuide.icon;

  return (
    <div className="space-y-6">
      {/* Assistant Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2.5">
          <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-emerald-500 to-blue-600 flex items-center justify-center shadow-sm">
            <Bot className="h-5 w-5 text-white" />
          </div>
          <div>
            <h3 className="font-bold text-sm text-foreground">
              {isIndonesian ? "Asisten Verifikasi" : "Verification Assistant"}
            </h3>
            <p className="text-[11px] text-muted-foreground">
              {isIndonesian ? "Panduan langkah demi langkah" : "Step-by-step guidance"}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant="ghost"
            size="sm"
            className="h-7 px-2 text-xs gap-1 text-muted-foreground"
            onClick={() => setAssistantLanguage(isIndonesian ? "en" : "id")}
          >
            <Globe className="h-3 w-3" />
            {isIndonesian ? "EN" : "ID"}
          </Button>
          <Button
            variant="ghost"
            size="sm"
            className="h-7 px-2 text-xs gap-1 text-muted-foreground"
            onClick={toggleGuide}
          >
            {state.isGuideActive ? (
              <>
                <X className="h-3 w-3" />
                {isIndonesian ? "Tutup" : "Close"}
              </>
            ) : (
              <>
                <StepForward className="h-3 w-3" />
                {isIndonesian ? "Panduan" : "Guide"}
              </>
            )}
          </Button>
        </div>
      </div>

      {/* Guided Walkthrough */}
      <AnimatePresence>
        {state.isGuideActive && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3 }}
            className="overflow-hidden"
          >
            <div className="rounded-2xl border border-emerald-200 dark:border-emerald-900/30 bg-gradient-to-br from-emerald-50 via-white to-blue-50 dark:from-emerald-950/20 dark:via-slate-900 dark:to-blue-950/20 p-5 shadow-sm">
              <div className="flex items-center gap-2 mb-3">
                <Progress value={progress} className="flex-1 h-1.5" />
                <span className="text-xs font-semibold text-muted-foreground shrink-0">
                  {state.currentGuideStep}/{guideSteps.length}
                </span>
              </div>

              <div className="flex items-start gap-3">
                <div className="w-8 h-8 rounded-full bg-emerald-100 dark:bg-emerald-900/40 flex items-center justify-center shrink-0">
                  <StepIcon className="h-4 w-4 text-emerald-600 dark:text-emerald-400" />
                </div>
                <div className="flex-1 min-w-0">
                  <h4 className="font-bold text-sm text-foreground mb-1">
                    {isIndonesian ? currentGuide.titleId : currentGuide.title}
                  </h4>
                  <p className="text-sm text-muted-foreground leading-relaxed">
                    {isIndonesian ? currentGuide.descriptionId : currentGuide.description}
                  </p>
                </div>
              </div>

              <div className="flex items-center justify-between mt-4 pt-3 border-t border-emerald-200/50 dark:border-emerald-900/20">
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-8 text-xs gap-1"
                  disabled={state.currentGuideStep === 1}
                  onClick={() =>
                    setGuideStep(
                      Math.max(1, state.currentGuideStep - 1) as GuideStep,
                    )
                  }
                >
                  <ChevronLeft className="h-3 w-3" />
                  {isIndonesian ? "Kembali" : "Back"}
                </Button>
                <div className="flex items-center gap-1">
                  {guideSteps.map((_, idx) => (
                    <button
                      key={idx}
                      onClick={() => setGuideStep((idx + 1) as GuideStep)}
                      className={`w-1.5 h-1.5 rounded-full transition-all ${
                        idx + 1 === state.currentGuideStep
                          ? "bg-emerald-600 dark:bg-emerald-400 w-3"
                          : "bg-slate-300 dark:bg-slate-600"
                      }`}
                      aria-label={`Step ${idx + 1}`}
                    />
                  ))}
                </div>
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-8 text-xs gap-1"
                  disabled={state.currentGuideStep === guideSteps.length}
                  onClick={() =>
                    setGuideStep(
                      Math.min(guideSteps.length, state.currentGuideStep + 1) as GuideStep,
                    )
                  }
                >
                  {isIndonesian ? "Lanjut" : "Next"}
                  <ChevronRight className="h-3 w-3" />
                </Button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Main Content Sections */}
      <div className="space-y-6">
        {/* Interactive Timeline */}
        <div className="rounded-2xl border border-border bg-card p-5 shadow-sm">
          <div className="flex items-center gap-2 mb-4">
            <Sprout className="h-5 w-5 text-emerald-600 dark:text-emerald-400" />
            <h3 className="font-bold text-sm text-foreground">
              {isIndonesian ? "Perjalanan Blockchain" : "Blockchain Journey"}
            </h3>
            <Badge
              variant="outline"
              className="text-[10px] px-1.5 py-0 h-4 ml-auto border-emerald-200 dark:border-emerald-800 text-emerald-700 dark:text-emerald-300"
            >
              {timelineSteps.length} {isIndonesian ? "langkah" : "steps"}
            </Badge>
          </div>
          <InteractiveTimeline steps={timelineSteps} />
        </div>

        {/* Trust Signals */}
        {trustSignals.length > 0 && (
          <div className="rounded-2xl border border-border bg-card p-5 shadow-sm">
            <div className="flex items-center gap-2 mb-4">
              <Sparkles className="h-5 w-5 text-blue-600 dark:text-blue-400" />
              <h3 className="font-bold text-sm text-foreground">
                {isIndonesian ? "Sinyal Verifikasi" : "Verification Signals"}
              </h3>
              <Badge
                variant="outline"
                className="text-[10px] px-1.5 py-0 h-4 ml-auto border-blue-200 dark:border-blue-800 text-blue-700 dark:text-blue-300"
              >
                {trustSignals.filter((s) => s.status === "verified").length}/
                {trustSignals.length}{" "}
                {isIndonesian ? "terverifikasi" : "verified"}
              </Badge>
            </div>
            <TrustSignalAccordion signals={trustSignals} />
          </div>
        )}

        {/* Recommendations */}
        {recommendations.length > 0 && (
          <div className="rounded-2xl border border-border bg-card p-5 shadow-sm">
            <div className="flex items-center gap-2 mb-4">
              <Lightbulb className="h-5 w-5 text-amber-600 dark:text-amber-400" />
              <h3 className="font-bold text-sm text-foreground">
                {isIndonesian ? "Rekomendasi" : "Recommendations"}
              </h3>
            </div>
            <ContextualRecommendations recommendations={recommendations} />
          </div>
        )}
      </div>

      {/* Floating Educational Content Toggle */}
      {state.showEducationalContent && (
        <div className="fixed bottom-24 right-6 z-40">
          <Button
            size="sm"
            variant="outline"
            className="h-9 rounded-full shadow-lg bg-card border-amber-200 dark:border-amber-800 gap-1.5 text-xs"
            onClick={() => toggleGuide()}
          >
            <Bot className="h-3.5 w-3.5 text-emerald-500" />
            {isIndonesian ? "Butuh Bantuan?" : "Need Help?"}
          </Button>
        </div>
      )}
    </div>
  );
}
